name: New problem

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'Problem label to create (A-Z, single uppercase character, without "p"-prefix)'

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install dos2unix python3-setuptools
          sudo python3 -m pip install psutil

      - name: Install tps
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/ioi-2017/tps/master/online-installer/install.sh)"

      - name: Download templates
        uses: actions/checkout@v3
        with:
          repository: 'TNFSH-Programming-Contest/tps-task-templates'
          path: 'tps-task-templates'

      - name: New problem
        run: |
          tps init p${{ inputs.label }} -T tps-task-templates

      - name: Modify README.md
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "<!-- new problem -->"
          replace: "| ${{ inputs.label }} | [statement](p${{ inputs.label }}/statement) [md](p${{ inputs.label }}/statement/index.md) [pdf](p${{ inputs.label }}/statement/index.pdf) | [gen](p${{ inputs.label }}/gen) | [validator](p${{ inputs.label }}/validator) | [solution](p${{ inputs.label }}/solution) [check](p${{ inputs.label }}/solutions-check.txt) | [tests](p${{ inputs.label }}/tests) | [problem](p${{ inputs.label }}/problem.json) [solutions](p${{ inputs.label }}/solutions.json) [subtasks](p${{ inputs.label }}/subtasks.json) |\n<!-- new problem -->"
          include: "README.md"

      - name: Check envs
        run: |
          pwd
          ls
          git status

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add p${{ inputs.label }}
          git add README.md
          git commit -m "Create problem p${{ inputs.label }}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
